theme: jekyll-theme-architect

title: [jms-spec]
description: [JMS (Java Message Service) Specification]

# sidebar links url
links:
  source: https://github.com/javaee/jms-spec
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

